### PR TITLE
Upgrade Vert.x Spring Boot to 0.0.4 and add AMQP

### PR DESCRIPTION
**Pull request by gytis**
#64

### CODE REVIEW

**Comment by gytis** [comment]
Ping @aureamunoz. Do you think we could add this to the 2.1.10 release?

**Comment by aureamunoz** [comment]
I don't know if I understand the question: the version `0.0.4` of `vertx-spring-boot` depends on SB 2.1.6 if I'm not wrong? https://github.com/snowdrop/vertx-spring-boot/blob/eb48e418fb24abe431b108a35ddd281e14374cb8/pom.xml#L53
Shouldn't do one depending on `2.1.10`? @gytis

**Comment by gytis** [comment]
Good point.  It was released before 2.1.10. You can ignore this pr. I'll
release 0.0.5 once I'm back and will raise a new pr with that in a couple
of days

**Comment by aureamunoz** [comment]
So, the `0.0.5` will depends on `2.1.10`, right? (The master now points to SB `2.2.0`)

**Comment by gytis** [comment]
Yes, I'll need to rebase and override the history. I updated the master to
2.2.0 a while ago since we were not planning to have any more 2.1.x bom
releases

**Comment by gytis** [comment]
Or just revert version commit and change it back after release

**Pull request closed without merging**
