### PR TITLE
Adding required spring framework/cloud deps that were missing w.r.t Brewery     App

### PR DESCRIPTION
**Pull request by kameshsampath**

### CODE REVIEW

**Comment by kameshsampath** [comment]
@cmoulliard - wondering we should use 
```
 <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

```
Instead of having each individual projects defined in the BOM - thoughts ?

**Comment by pavolloffay** [comment]
I think `x-dependencies` is better from the maintenance perspective (if we are going to use the same versions as original SB stack)

**Comment by kameshsampath** [comment]
thanks @pavolloffay , I shall make the needed updates, test it locally , add that commit to this.

**Comment by pavolloffay** [comment]
It's not my call, however, I used that in OpenTracing integrations.

**Comment by kameshsampath** [comment]
@cmoulliard thoughts ???

**Comment by cmoulliard** [comment]
@kameshsampath Can you rebase as there is a conflict ?

**Comment by kameshsampath** [comment]
@cmoulliard -  I am sorry, that I had sent the PR to the `master` instead of `sb-1.5.x` branch of upstream, corrected my pull. please verify and let me know if any updates required.

Also any thoughts on using Spring BOM's instead of explicit dependencies ??

**Pull request merged**
