### PR TITLE
fixes for release 2.3.4

### PR DESCRIPTION
**Pull request by jacobdotcosta**
This is the `pom.xml` cooked for 2.3.4.

### CODE REVIEW

**Review by metacosm — CHANGES_REQUESTED** [review]
Missing upgrade to Infinispan 11.0.3.
Missing upgrade to Hibernate Validator 6.0.20.
Missing upgrade to Jaeger starter (though, at this point, I'm confused about the information in the JIRA ticket) :(
Otherwise, I *think* we're OK.

**Comment by jacobdotcosta** [comment]
> Missing upgrade to Infinispan 11.0.3.
> Missing upgrade to Hibernate Validator 6.0.20.
> Missing upgrade to Jaeger starter (though, at this point, I'm confused about the information in the JIRA ticket) :(
> Otherwise, I _think_ we're OK.

I had doubts regarding Infinispan and Hibernate Validator. Since they are inherited from Spring Boot I thought they only had to be changed in the downstream project and not the upstream. Can you confirm that we should change them upstream also?

I think opentracing-spring-jaeger-web-starter has version 4.0.0. https://github.com/opentracing-contrib/java-spring-web/releases/tag/4.0.0

**Comment by metacosm** [comment]
For Infinispan, we need to update it since we import its BOM and not doing so might cause issues in the starter. 
For Hibernate Validator, that is indeed debatable. 
For OpenTracing, I have no idea and the point of the JIRAs is that we **shouldn't** be guessing. We need that information properly recorded in JIRA before we can act on it.

**Comment by jacobdotcosta** [comment]
I have red it again and it's `3.2.1` because we're using `io.opentracing.contrib:opentracing-spring-jaeger-web-starter` and not `io.opentracing.contrib:opentracing-spring-web-starter` and the former is part of the `io.opentracing.contrib:opentracing-spring-jaeger-parent` which was released under version `3.2.1`.

**Comment by aureamunoz** [comment]
> I have red it again and it's `3.2.1` because we're using `io.opentracing.contrib:opentracing-spring-jaeger-web-starter` and not `io.opentracing.contrib:opentracing-spring-web-starter` and the former is part of the `io.opentracing.contrib:opentracing-spring-jaeger-parent` which was released under version `3.2.1`.

yes, and this what you used in the PR,so it's ok.

**Comment by jacobdotcosta** [comment]
Since the hibernate validator has been confirmed to be left as comes from Spring Boot, I'll merge this PR. Check the release JIRA for more information.

**Pull request merged**
