### PR TITLE
Use latest SB 2.1 compatible SCK starter

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gytis** [comment]
I assume we're ignoring the CI for now?

**Comment by geoand** [comment]
Yeah, let's ignore it for the time being since it will just slow us down

**Comment by geoand** [comment]
Well if we see and dependency resolution failures we obviously need to fix em :)

**Comment by geoand** [comment]
Actually, I disable the health check booster for now and see what happens

**Pull request merged**
