### PR TITLE
Sb 2.1.x upgrade narayana and amqp

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
Yes the test failed on CXF, which is unrelated. We should upgrade Spring Boot version too, that might help with tests

**Comment by geoand** [comment]
@gytis How about we don't use the http booster, but instead switch to the health check booster for this?
At least until we sort out the CXF stuff...

Would you like to update the CircleCI config `sb-2.1.x` as part of this PR or do you want me to do it separately?

**Comment by geoand** [comment]
> Yes the test failed on CXF, which is unrelated. We should upgrade Spring Boot version too, that might help with tests

The spring boot version is automatically set for the PR from the BOM version

**Comment by gytis** [comment]
@geoand doesn't spring boot version in bom influence that?

**Comment by geoand** [comment]
@gytis https://github.com/snowdrop/spring-boot-bom/blob/aa6f5b0d5117cb6b52295e4f6ff1b747f9f92510/.circleci/config.yml#L85

We pull the spring boot version from the name of the branch, so it should just work :P

**Comment by geoand** [comment]
Damn it... health booster needs an update to work with SB 2.x...

**Comment by gytis** [comment]
Not sure. But I think it would be time to start upgrading them anyway.

**Comment by geoand** [comment]
OK, I will update the health check booster to 2.1 and have it on a dedicated branch. Then these tests could use that branch

**Comment by gytis** [comment]
I can look into it too if you're busy

**Comment by geoand** [comment]
I have started to look into it, but I'm getting a weird error from the infinispan BOM.... Can you perhaps check and see if you have the same problem?

I simply "installed" the 2.1.x version of the BOM locally and tried to use it in the health check booster

**Comment by gytis** [comment]
I get the error too

**Comment by geoand** [comment]
Something might be wrong with that BOM. For the moment I just commented it out in our BOM to get past the problem

**Comment by geoand** [comment]
@gytis Can you update the CircleCI config of the PR to use branch `2.1.x` of the booster please?

**Comment by geoand** [comment]
I think we should go ahead and merge. We need to make a lot of changes anyway before anything get's working properly...

**Pull request merged**
